name: deploy
on: push
jobs:
  deploy:
      runs-on: ununtu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v3
      
        - name: Install dependencies
          run: npm ci
        - name: echolint
          run: echo "lint"
        - name: run lint
          run: lint
        - name: run test
          run: test/setup.js
        - name: deploy
          run: echo 'Deploy"'
    